# Generated by Django 4.2.9 on 2025-12-09 18:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Quarto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10, verbose_name='Código do quarto')),
                ('piso', models.CharField(choices=[('RC', 'Rés-do-chão'), ('1', '1.º Piso'), ('2', '2.º Piso'), ('3', '3.º Piso')], max_length=2, verbose_name='Piso')),
                ('descricao', models.CharField(blank=True, max_length=100, null=True, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Quarto',
                'verbose_name_plural': 'Quartos',
                'ordering': ['piso', 'codigo'],
                'unique_together': {('codigo', 'piso')},
            },
        ),
        migrations.CreateModel(
            name='Utente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome completo')),
                ('data_nascimento', models.DateField(blank=True, null=True, verbose_name='Data de nascimento')),
                ('numero_processo', models.CharField(max_length=50, unique=True, verbose_name='N.º processo')),
                ('data_entrada', models.DateField(verbose_name='Data de entrada')),
                ('data_saida', models.DateField(blank=True, null=True, verbose_name='Data de saída')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('quarto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='utentes', to='visitas.quarto', verbose_name='Quarto')),
                ('registado_entrada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='utentes_registados_entrada', to=settings.AUTH_USER_MODEL, verbose_name='Entrada registada por')),
                ('registado_saida_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='utentes_registados_saida', to=settings.AUTH_USER_MODEL, verbose_name='Saída registada por')),
            ],
            options={
                'verbose_name': 'Utente',
                'verbose_name_plural': 'Utentes',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Visita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_visitante', models.CharField(choices=[('FAM', 'Familiar / Amigo'), ('VOL', 'Voluntário'), ('OUT', 'Outro')], default='FAM', max_length=4, verbose_name='Tipo de visitante')),
                ('nome_visitante', models.CharField(max_length=200, verbose_name='Nome do visitante')),
                ('documento_identificacao', models.CharField(blank=True, max_length=100, null=True, verbose_name='Documento identificação')),
                ('telefone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone')),
                ('parentesco', models.CharField(blank=True, help_text='Ex.: filho, irmã, amigo. Pode ficar em branco se não se aplicar.', max_length=100, null=True, verbose_name='Parentesco com o utente')),
                ('data_hora_entrada', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data e hora de entrada')),
                ('data_hora_saida', models.DateTimeField(blank=True, null=True, verbose_name='Data e hora de saída')),
                ('motivo', models.CharField(blank=True, max_length=200, null=True, verbose_name='Motivo da visita')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('registado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visitas_registadas', to=settings.AUTH_USER_MODEL, verbose_name='Registado por')),
                ('utente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitas', to='visitas.utente', verbose_name='Utente visitado')),
            ],
            options={
                'verbose_name': 'Visita',
                'verbose_name_plural': 'Visitas',
                'ordering': ['-data_hora_entrada'],
            },
        ),
        migrations.CreateModel(
            name='Externo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_externo', models.CharField(choices=[('SERV', 'Prestador de serviços'), ('TEC', 'Técnico / Manutenção'), ('FORN', 'Fornecedor'), ('OUT', 'Outro')], default='SERV', max_length=5, verbose_name='Tipo de externo')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome')),
                ('empresa', models.CharField(blank=True, max_length=150, null=True, verbose_name='Empresa / Entidade')),
                ('documento_identificacao', models.CharField(blank=True, max_length=100, null=True, verbose_name='Documento identificação')),
                ('telefone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone')),
                ('destino', models.CharField(blank=True, help_text='Ex.: Manutenção, Direção Técnica, Administração...', max_length=150, null=True, verbose_name='Destino / Setor')),
                ('data_hora_entrada', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data e hora de entrada')),
                ('data_hora_saida', models.DateTimeField(blank=True, null=True, verbose_name='Data e hora de saída')),
                ('motivo', models.CharField(blank=True, max_length=200, null=True, verbose_name='Motivo da presença')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('registado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='externos_registados', to=settings.AUTH_USER_MODEL, verbose_name='Registado por')),
            ],
            options={
                'verbose_name': 'Registo externo',
                'verbose_name_plural': 'Registos externos',
                'ordering': ['-data_hora_entrada'],
            },
        ),
    ]
