# Generated by Django 4.2.9 on 2025-12-10 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='utente',
            name='alerta_visitas',
            field=models.TextField(blank=True, help_text='Texto a mostrar quando alguém regista uma visita a este utente.', null=True, verbose_name='Alerta para visitas'),
        ),
        migrations.AddField(
            model_name='utente',
            name='data_prevista_saida',
            field=models.DateField(blank=True, null=True, verbose_name='Data prevista de saída'),
        ),
        migrations.AddField(
            model_name='utente',
            name='genero',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outro / Não especificado')], max_length=1, null=True, verbose_name='Género'),
        ),
        migrations.AddField(
            model_name='utente',
            name='numero_utente_sns',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='N.º Utente SNS'),
        ),
        migrations.AddField(
            model_name='utente',
            name='tipo_alta',
            field=models.CharField(blank=True, choices=[('NORMAL', 'Saída normal'), ('OBITO', 'Óbito'), ('PERDA_VAGA', 'Perda de vaga')], help_text='Preencher aquando da saída/alta.', max_length=20, null=True, verbose_name='Tipo de alta'),
        ),
        migrations.AddField(
            model_name='utente',
            name='tipo_internamento',
            field=models.CharField(blank=True, choices=[('UC', 'Convalescença (U.C.)'), ('UMDR', 'UMDR'), ('ULDM', 'ULDM'), ('ULDM-DC', 'ULDM-DC')], max_length=10, null=True, verbose_name='Tipo de internamento'),
        ),
        migrations.AddField(
            model_name='utente',
            name='visitas_restritas',
            field=models.BooleanField(default=False, help_text='Ativar se este utente tiver restrição de visitas.', verbose_name='Visitas restritas'),
        ),
    ]
