# Generated by Django 4.2.9 on 2025-12-10 15:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('visitas', '0002_utente_alerta_visitas_utente_data_prevista_saida_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='externo',
            options={'ordering': ['-data_hora_entrada']},
        ),
        migrations.AlterModelOptions(
            name='visita',
            options={'ordering': ['-data_hora_entrada']},
        ),
        migrations.AddField(
            model_name='utente',
            name='transferido_para',
            field=models.CharField(blank=True, help_text='Indicar local/unidade para onde foi transferido.', max_length=200, null=True, verbose_name='Transferido para'),
        ),
        migrations.AlterField(
            model_name='externo',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='externo',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='externo',
            name='data_hora_entrada',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='externo',
            name='data_hora_saida',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='externo',
            name='destino',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='externo',
            name='documento_identificacao',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='externo',
            name='empresa',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='externo',
            name='motivo',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='externo',
            name='nome',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='externo',
            name='observacoes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='externo',
            name='registado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='externos_registados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='externo',
            name='telefone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='externo',
            name='tipo_externo',
            field=models.CharField(choices=[('SERV', 'Prestador de serviços'), ('TEC', 'Técnico / Manutenção'), ('FORN', 'Fornecedor'), ('OUT', 'Outro')], default='SERV', max_length=5),
        ),
        migrations.AlterField(
            model_name='utente',
            name='alerta_visitas',
            field=models.TextField(blank=True, null=True, verbose_name='Alerta para visitas'),
        ),
        migrations.AlterField(
            model_name='utente',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='utente',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='utente',
            name='registado_entrada_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='utentes_registados_entrada', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='utente',
            name='registado_saida_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='utentes_registados_saida', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='utente',
            name='tipo_alta',
            field=models.CharField(blank=True, choices=[('NORMAL', 'Saída normal'), ('OBITO', 'Óbito'), ('PERDA_VAGA', 'Perda de vaga'), ('TRANSFERENCIA', 'Transferência')], max_length=20, null=True, verbose_name='Tipo de alta'),
        ),
        migrations.AlterField(
            model_name='utente',
            name='tipo_internamento',
            field=models.CharField(blank=True, choices=[('UC', 'Convalescença (U.C.)'), ('UMDR', 'UMDR'), ('ULDM', 'ULDM'), ('ULDM-DC', 'ULDM-DC')], max_length=15, null=True, verbose_name='Tipo de internamento'),
        ),
        migrations.AlterField(
            model_name='utente',
            name='visitas_restritas',
            field=models.BooleanField(default=False, verbose_name='Visitas restritas'),
        ),
        migrations.AlterField(
            model_name='visita',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='visita',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='visita',
            name='data_hora_entrada',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Entrada'),
        ),
        migrations.AlterField(
            model_name='visita',
            name='data_hora_saida',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Saída'),
        ),
        migrations.AlterField(
            model_name='visita',
            name='motivo',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Motivo'),
        ),
        migrations.AlterField(
            model_name='visita',
            name='parentesco',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Parentesco'),
        ),
        migrations.AlterField(
            model_name='visita',
            name='registado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visitas_registadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='visita',
            name='utente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitas', to='visitas.utente'),
        ),
    ]
