# Generated by Django 4.2.9 on 2025-12-19 16:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('visitas', '0003_alter_externo_options_alter_visita_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Isolamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('CONTACTO', 'Isolamento de contacto'), ('GOTICULAS', 'Isolamento por gotículas'), ('VIA_AEREA', 'Isolamento por via aérea')], max_length=20)),
                ('ativo', models.BooleanField(default=True)),
                ('data_inicio', models.DateTimeField(default=django.utils.timezone.now)),
                ('data_fim', models.DateTimeField(blank=True, null=True)),
                ('motivo', models.CharField(blank=True, default='', max_length=255)),
                ('observacoes', models.TextField(blank=True, default='')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('terminado_em', models.DateTimeField(blank=True, null=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='isolamentos_criados', to=settings.AUTH_USER_MODEL)),
                ('terminado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='isolamentos_terminados', to=settings.AUTH_USER_MODEL)),
                ('utente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='isolamentos', to='visitas.utente')),
            ],
            options={
                'ordering': ['-ativo', '-data_inicio'],
            },
        ),
    ]
