# Generated by Django 4.2.9 on 2026-08-12 14:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('visitas', '0005_utente_contacto_emergencia1_nome_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Condutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=180, verbose_name='Nome')),
                ('numero_mecanografico', models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='N.º mecanográfico')),
                ('telefone', models.CharField(blank=True, max_length=30, verbose_name='Telefone')),
                ('categoria_carta', models.CharField(blank=True, max_length=30, verbose_name='Categoria da carta')),
                ('numero_carta', models.CharField(blank=True, max_length=50, verbose_name='N.º da carta')),
                ('validade_carta', models.DateField(blank=True, null=True, verbose_name='Validade da carta')),
                ('ativo', models.BooleanField(default=True, verbose_name='Disponível para marcação')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Condutor',
                'verbose_name_plural': 'Condutores',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Viatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(max_length=15, unique=True, verbose_name='Matrícula')),
                ('designacao', models.CharField(max_length=120, verbose_name='Designação')),
                ('tipo', models.CharField(choices=[('LIGEIRA', 'Ligeira'), ('ADAPTADA', 'Adaptada'), ('AMBULANCIA', 'Ambulância'), ('OUTRA', 'Outra')], default='LIGEIRA', max_length=15, verbose_name='Tipo de viatura')),
                ('marca', models.CharField(blank=True, max_length=80, verbose_name='Marca')),
                ('modelo', models.CharField(blank=True, max_length=80, verbose_name='Modelo')),
                ('numero_lugares', models.PositiveSmallIntegerField(default=5, verbose_name='N.º de lugares')),
                ('adaptada_cadeira_rodas', models.BooleanField(default=False, verbose_name='Preparada para cadeira de rodas')),
                ('permite_maca', models.BooleanField(default=False, verbose_name='Permite transporte em maca')),
                ('validade_seguro', models.DateField(blank=True, null=True, verbose_name='Validade do seguro')),
                ('validade_inspecao', models.DateField(blank=True, null=True, verbose_name='Validade da inspeção')),
                ('ativo', models.BooleanField(default=True, verbose_name='Disponível para marcação')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Viatura',
                'verbose_name_plural': 'Viaturas',
                'ordering': ['matricula'],
            },
        ),
        migrations.CreateModel(
            name='Indisponibilidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio', models.DateTimeField(verbose_name='Início')),
                ('fim', models.DateTimeField(verbose_name='Fim')),
                ('motivo', models.CharField(max_length=250, verbose_name='Motivo')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('condutor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='indisponibilidades', to='visitas.condutor')),
                ('criado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='indisponibilidades_transporte_criadas', to=settings.AUTH_USER_MODEL)),
                ('viatura', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='indisponibilidades', to='visitas.viatura')),
            ],
            options={
                'verbose_name': 'Indisponibilidade',
                'verbose_name_plural': 'Indisponibilidades',
                'ordering': ['-inicio'],
            },
        ),
        migrations.CreateModel(
            name='Transporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_deslocacao', models.CharField(choices=[('CONSULTA', 'Consulta'), ('EXAME', 'Exame'), ('TRATAMENTO', 'Tratamento'), ('URGENCIA', 'Urgência'), ('TRANSFERENCIA', 'Transferência temporária'), ('OUTRO', 'Outro')], default='CONSULTA', max_length=20, verbose_name='Tipo de deslocação')),
                ('motivo', models.CharField(max_length=250, verbose_name='Motivo')),
                ('destino', models.CharField(max_length=250, verbose_name='Destino')),
                ('data_hora_saida', models.DateTimeField(verbose_name='Saída prevista da UCCI')),
                ('data_hora_consulta', models.DateTimeField(blank=True, null=True, verbose_name='Hora da consulta/exame')),
                ('data_hora_regresso_previsto', models.DateTimeField(verbose_name='Regresso previsto à UCCI')),
                ('data_hora_saida_real', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Saída efetiva')),
                ('data_hora_regresso_real', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Regresso efetivo')),
                ('meio_transporte', models.CharField(choices=[('INSTITUICAO', 'Viatura da instituição'), ('AMBULANCIA', 'Ambulância externa'), ('TAXI', 'Táxi / TVDE'), ('FAMILIA', 'Família'), ('OUTRO', 'Outro')], default='INSTITUICAO', max_length=20, verbose_name='Meio de transporte')),
                ('entidade_transporte', models.CharField(blank=True, help_text='Ex.: Bombeiros, táxi ou familiar.', max_length=180, verbose_name='Entidade/pessoa responsável pelo transporte')),
                ('acompanhante_nome', models.CharField(blank=True, max_length=180, verbose_name='Acompanhante')),
                ('acompanhante_contacto', models.CharField(blank=True, max_length=30, verbose_name='Contacto do acompanhante')),
                ('necessita_cadeira_rodas', models.BooleanField(default=False, verbose_name='Cadeira de rodas')),
                ('necessita_maca', models.BooleanField(default=False, verbose_name='Maca')),
                ('necessita_oxigenio', models.BooleanField(default=False, verbose_name='Oxigénio')),
                ('outras_necessidades', models.CharField(blank=True, max_length=250, verbose_name='Outras necessidades')),
                ('estado', models.CharField(choices=[('PENDENTE', 'Pendente'), ('CONFIRMADO', 'Confirmado'), ('EM_CURSO', 'Em curso'), ('CONCLUIDO', 'Concluído'), ('CANCELADO', 'Cancelado')], default='PENDENTE', max_length=15, verbose_name='Estado')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('atualizado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transportes_atualizados', to=settings.AUTH_USER_MODEL)),
                ('condutor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transportes', to='visitas.condutor', verbose_name='Condutor')),
                ('criado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transportes_criados', to=settings.AUTH_USER_MODEL)),
                ('utente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transportes', to='visitas.utente', verbose_name='Utente')),
                ('viatura', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transportes', to='visitas.viatura', verbose_name='Viatura')),
            ],
            options={
                'verbose_name': 'Transporte de utente',
                'verbose_name_plural': 'Transportes de utentes',
                'ordering': ['data_hora_saida'],
                'indexes': [models.Index(fields=['data_hora_saida', 'data_hora_regresso_previsto'], name='visitas_tra_data_ho_5c9590_idx'), models.Index(fields=['estado'], name='visitas_tra_estado_2ff452_idx')],
            },
        ),
    ]
