# Generated by Django 4.2.9 on 2026-08-29 00:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('visitas', '0006_condutor_viatura_indisponibilidade_transporte'),
    ]

    operations = [
        migrations.CreateModel(
            name='PedidoTransporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_deslocacao', models.CharField(choices=[('CONSULTA', 'Consulta'), ('EXAME', 'Exame'), ('TRATAMENTO', 'Tratamento'), ('URGENCIA', 'Urgência'), ('TRANSFERENCIA', 'Transferência temporária'), ('OUTRO', 'Outro')], default='CONSULTA', max_length=20, verbose_name='Tipo de deslocação')),
                ('motivo', models.CharField(max_length=250, verbose_name='Motivo')),
                ('destino', models.CharField(max_length=250, verbose_name='Destino')),
                ('data_hora_consulta', models.DateTimeField(blank=True, null=True, verbose_name='Hora da consulta/exame')),
                ('data_hora_saida', models.DateTimeField(blank=True, null=True, verbose_name='Saída prevista da UCCI')),
                ('data_hora_regresso_previsto', models.DateTimeField(blank=True, null=True, verbose_name='Regresso previsto à UCCI')),
                ('meio_transporte', models.CharField(blank=True, choices=[('INSTITUICAO', 'Viatura da instituição'), ('AMBULANCIA', 'Ambulância externa'), ('TAXI', 'Táxi / TVDE'), ('FAMILIA', 'Família'), ('OUTRO', 'Outro')], default='', max_length=20, verbose_name='Meio de transporte')),
                ('entidade_transporte', models.CharField(blank=True, help_text='Ex.: Bombeiros, táxi ou familiar.', max_length=180, verbose_name='Entidade/pessoa responsável pelo transporte')),
                ('acompanhante_nome', models.CharField(blank=True, max_length=180, verbose_name='Acompanhante')),
                ('acompanhante_contacto', models.CharField(blank=True, max_length=30, verbose_name='Contacto do acompanhante')),
                ('necessita_cadeira_rodas', models.BooleanField(default=False, verbose_name='Cadeira de rodas')),
                ('necessita_maca', models.BooleanField(default=False, verbose_name='Maca')),
                ('necessita_oxigenio', models.BooleanField(default=False, verbose_name='Oxigénio')),
                ('outras_necessidades', models.CharField(blank=True, max_length=250, verbose_name='Outras necessidades')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações do pedido')),
                ('estado', models.CharField(choices=[('POR_VALIDAR', 'A validar pela Receção'), ('DEVOLVIDO', 'Devolvido para correção'), ('VALIDADO', 'Validado'), ('REJEITADO', 'Rejeitado'), ('CANCELADO', 'Cancelado')], default='POR_VALIDAR', max_length=15, verbose_name='Estado do pedido')),
                ('observacoes_recepcao', models.TextField(blank=True, verbose_name='Observações da Receção')),
                ('validado_em', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Validado em')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('condutor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pedidos_transporte', to='visitas.condutor', verbose_name='Condutor')),
                ('pedido_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_transporte_criados', to=settings.AUTH_USER_MODEL, verbose_name='Pedido por')),
                ('transporte', models.OneToOneField(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedido_origem', to='visitas.transporte', verbose_name='Transporte criado')),
                ('utente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos_transporte', to='visitas.utente', verbose_name='Utente')),
                ('validado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_transporte_validados', to=settings.AUTH_USER_MODEL, verbose_name='Validado por')),
                ('viatura', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pedidos_transporte', to='visitas.viatura', verbose_name='Viatura')),
            ],
            options={
                'verbose_name': 'Pedido de transporte',
                'verbose_name_plural': 'Pedidos de transporte',
                'ordering': ['-criado_em'],
                'indexes': [models.Index(fields=['estado', 'criado_em'], name='visitas_ped_estado_9cd73f_idx')],
            },
        ),
    ]
