# Generated by Django 4.2.9 on 2026-08-28 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitas', '0006_condutor_viatura_indisponibilidade_transporte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transporte',
            name='destino',
            field=models.CharField(blank=True, max_length=250, verbose_name='Destino'),
        ),
        migrations.AlterField(
            model_name='transporte',
            name='meio_transporte',
            field=models.CharField(blank=True, choices=[('INSTITUICAO', 'Viatura da instituição'), ('AMBULANCIA', 'Ambulância externa'), ('TAXI', 'Táxi / TVDE'), ('FAMILIA', 'Família'), ('OUTRO', 'Outro')], default='INSTITUICAO', max_length=20, verbose_name='Meio de transporte'),
        ),
        migrations.AlterField(
            model_name='transporte',
            name='motivo',
            field=models.CharField(blank=True, max_length=250, verbose_name='Motivo'),
        ),
        migrations.AlterField(
            model_name='transporte',
            name='tipo_deslocacao',
            field=models.CharField(blank=True, choices=[('CONSULTA', 'Consulta'), ('EXAME', 'Exame'), ('TRATAMENTO', 'Tratamento'), ('URGENCIA', 'Urgência'), ('TRANSFERENCIA', 'Transferência temporária'), ('OUTRO', 'Outro')], default='CONSULTA', max_length=20, verbose_name='Tipo de deslocação'),
        ),
    ]
