# Generated by Django 4.2.9 on 2026-08-29 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitas', '0007_pedidotransporte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidotransporte',
            name='destino',
            field=models.CharField(blank=True, max_length=250, verbose_name='Destino'),
        ),
        migrations.AlterField(
            model_name='pedidotransporte',
            name='motivo',
            field=models.CharField(blank=True, max_length=250, verbose_name='Motivo'),
        ),
    ]
