# Generated by Django 4.2.9 on 2026-08-29 01:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('visitas', '0008_alter_pedidotransporte_destino_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transporte',
            name='confirmado_em',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Confirmado em'),
        ),
        migrations.AddField(
            model_name='transporte',
            name='confirmado_por',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transportes_confirmados', to=settings.AUTH_USER_MODEL, verbose_name='Confirmado por'),
        ),
    ]
