# Generated by Django 4.2.9 on 2026-09-02 14:14

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('visitas', '0009_transporte_confirmado_em_transporte_confirmado_por'),
    ]

    operations = [
        migrations.AddField(
            model_name='utente',
            name='paga_dias_ausencia',
            field=models.BooleanField(default=True, verbose_name='Paga durante as ausências'),
        ),
        migrations.AddField(
            model_name='utente',
            name='valor_dia',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8, verbose_name='Valor diário'),
        ),
        migrations.CreateModel(
            name='Mensalidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.PositiveIntegerField()),
                ('mes', models.PositiveSmallIntegerField()),
                ('valor_dia', models.DecimalField(decimal_places=2, max_digits=8)),
                ('dias_faturaveis', models.PositiveIntegerField(default=0)),
                ('valor_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('pago', models.BooleanField(default=False, verbose_name='Pago')),
                ('pago_em', models.DateTimeField(blank=True, null=True)),
                ('confirmado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mensalidades_confirmadas', to=settings.AUTH_USER_MODEL)),
                ('utente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mensalidades', to='visitas.utente')),
            ],
            options={
                'ordering': ['-ano', '-mes', 'utente__nome'],
            },
        ),
        migrations.AddConstraint(
            model_name='mensalidade',
            constraint=models.UniqueConstraint(fields=('utente', 'ano', 'mes'), name='mensalidade_unica_por_utente_mes'),
        ),
    ]
