# Generated by Django 4.2.9 on 2026-09-02 14:38

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('visitas', '0010_utente_paga_dias_ausencia_utente_valor_dia_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mensalidade',
            options={'ordering': ['-ano', '-mes', 'utente__nome'], 'verbose_name': 'Mensalidade do utente', 'verbose_name_plural': 'Mensalidades dos utentes'},
        ),
        migrations.AddField(
            model_name='mensalidade',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='mensalidade',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mensalidade',
            name='dias_ausencia',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Dias de ausência descontados'),
        ),
        migrations.AddField(
            model_name='mensalidade',
            name='dias_estadia',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Dias de estadia no mês'),
        ),
        migrations.AddField(
            model_name='mensalidade',
            name='necessita_revisao',
            field=models.BooleanField(db_index=True, default=False, help_text='Indica que uma mensalidade já paga foi recalculada devido a uma alteração de datas, ausências ou valor diário.', verbose_name='Necessita de revisão'),
        ),
        migrations.AddField(
            model_name='mensalidade',
            name='observacoes',
            field=models.TextField(blank=True, verbose_name='Observações'),
        ),
        migrations.AddField(
            model_name='quarto',
            name='capacidade',
            field=models.PositiveSmallIntegerField(default=1, help_text='Número de camas disponíveis neste quarto.', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Número de camas'),
        ),
        migrations.AlterField(
            model_name='mensalidade',
            name='ano',
            field=models.PositiveSmallIntegerField(verbose_name='Ano'),
        ),
        migrations.AlterField(
            model_name='mensalidade',
            name='confirmado_por',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mensalidades_confirmadas', to=settings.AUTH_USER_MODEL, verbose_name='Confirmado por'),
        ),
        migrations.AlterField(
            model_name='mensalidade',
            name='dias_faturaveis',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Dias faturáveis'),
        ),
        migrations.AlterField(
            model_name='mensalidade',
            name='mes',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='Mês'),
        ),
        migrations.AlterField(
            model_name='mensalidade',
            name='pago',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Pago'),
        ),
        migrations.AlterField(
            model_name='mensalidade',
            name='pago_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Pago em'),
        ),
        migrations.AlterField(
            model_name='mensalidade',
            name='utente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mensalidades', to='visitas.utente', verbose_name='Utente'),
        ),
        migrations.AlterField(
            model_name='mensalidade',
            name='valor_dia',
            field=models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Valor diário aplicado'),
        ),
        migrations.AlterField(
            model_name='mensalidade',
            name='valor_total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Valor total'),
        ),
        migrations.AlterField(
            model_name='utente',
            name='paga_dias_ausencia',
            field=models.BooleanField(default=True, help_text='Desative para descontar da mensalidade os dias em que o utente está ausente.', verbose_name='Paga durante as ausências'),
        ),
        migrations.AlterField(
            model_name='utente',
            name='valor_dia',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Valor cobrado por cada dia faturável de internamento.', max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Valor diário'),
        ),
        migrations.AddIndex(
            model_name='mensalidade',
            index=models.Index(fields=['ano', 'mes', 'pago'], name='vis_mens_ano_mes_pago'),
        ),
    ]
