# Generated by Django 4.2.9 on 2026-09-02 16:15

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('visitas', '0011_alter_mensalidade_options_mensalidade_atualizado_em_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PagamentoMensalidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Valor recebido')),
                ('data_pagamento', models.DateField(default=django.utils.timezone.localdate, verbose_name='Data do pagamento')),
                ('observacoes', models.CharField(blank=True, max_length=250, verbose_name='Observações')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Registado em')),
                ('mensalidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagamentos', to='visitas.mensalidade', verbose_name='Mensalidade')),
                ('registado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagamentos_mensalidades_registados', to=settings.AUTH_USER_MODEL, verbose_name='Registado por')),
            ],
            options={
                'verbose_name': 'Pagamento de mensalidade',
                'verbose_name_plural': 'Pagamentos de mensalidades',
                'ordering': ['-data_pagamento', '-criado_em'],
                'indexes': [models.Index(fields=['mensalidade', 'data_pagamento'], name='vis_pag_mens_data')],
            },
        ),
    ]
