# Generated by Django 4.2.9 on 2026-08-29 22:52

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('visitas', '0009_transporte_confirmado_em_transporte_confirmado_por'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistoEnfermagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_registo', models.DateTimeField(verbose_name='Data e hora do registo')),
                ('turno', models.CharField(blank=True, choices=[('MANHA', 'Manhã'), ('TARDE', 'Tarde'), ('NOITE', 'Noite'), ('OUTRO', 'Outro')], max_length=20, verbose_name='Turno')),
                ('observacao', models.TextField(help_text='Descreva o estado, evolução e informação relevante observada no utente.', verbose_name='Observação e evolução')),
                ('cuidados_realizados', models.TextField(blank=True, verbose_name='Cuidados e intervenções realizadas')),
                ('resposta_utente', models.TextField(blank=True, verbose_name='Resposta do utente')),
                ('plano_cuidados', models.TextField(blank=True, verbose_name='Plano e recomendações seguintes')),
                ('visibilidade', models.CharField(choices=[('CONFIDENCIAL', 'Apenas eu'), ('GRUPO', 'Grupo profissional'), ('TODOS', 'Equipas clínicas autorizadas')], default='TODOS', help_text='Por defeito, o registo fica disponível para as equipas configuradas na área clínica.', max_length=20, verbose_name='Visibilidade')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('profissional', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registos_enfermagem_criados', to=settings.AUTH_USER_MODEL, verbose_name='Profissional')),
            ],
            options={
                'verbose_name': 'Registo de Enfermagem',
                'verbose_name_plural': 'Registos de Enfermagem',
                'ordering': ['-data_registo', '-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='TipoRegistoEnfermagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.SlugField(help_text='Identificador interno. Não deve ser alterado depois de existirem registos.', unique=True, verbose_name='Código')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('ordem', models.PositiveSmallIntegerField(default=0, verbose_name='Ordem')),
            ],
            options={
                'verbose_name': 'Tipo de registo de Enfermagem',
                'verbose_name_plural': 'Tipos de registo de Enfermagem',
                'ordering': ['ordem', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='RegistoQueda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora_queda', models.DateTimeField(verbose_name='Data e hora da queda')),
                ('local_queda', models.CharField(choices=[('QUARTO', 'Quarto'), ('CASA_BANHO', 'Casa de banho'), ('CORREDOR', 'Corredor'), ('SALA', 'Sala'), ('REFEITORIO', 'Refeitório'), ('FISIOTERAPIA', 'Fisioterapia'), ('EXTERIOR', 'Exterior'), ('OUTRO', 'Outro')], max_length=30, verbose_name='Local da queda')),
                ('local_detalhe', models.CharField(blank=True, help_text='Exemplo: quarto 12, junto à cama ou casa de banho do piso 1.', max_length=200, verbose_name='Indicação adicional do local')),
                ('tipo_queda', models.CharField(choices=[('PROPRIA_ALTURA', 'Da própria altura'), ('CAMA', 'Da cama'), ('CADEIRA', 'De cadeira ou cadeirão'), ('TRANSFERENCIA', 'Durante transferência'), ('MARCHA', 'Durante a marcha'), ('ESCADAS', 'Em escadas'), ('OUTRO', 'Outro')], max_length=30, verbose_name='Tipo de queda')),
                ('testemunhada', models.BooleanField(default=False, verbose_name='Queda testemunhada')),
                ('testemunhas', models.CharField(blank=True, max_length=250, verbose_name='Testemunhas')),
                ('descricao_ocorrencia', models.TextField(help_text='Descreva como aconteceu a queda ou como o utente foi encontrado.', verbose_name='Descrição da ocorrência')),
                ('atividade_no_momento', models.TextField(blank=True, help_text='Exemplo: levantar-se da cama, caminhar ou deslocar-se à casa de banho.', verbose_name='Atividade no momento da queda')),
                ('fatores_contribuintes', models.TextField(blank=True, help_text='Exemplo: piso molhado, desorientação, calçado, medicação ou falta de apoio.', verbose_name='Possíveis fatores contribuintes')),
                ('gravidade', models.CharField(choices=[('SEM_LESAO', 'Sem lesão aparente'), ('LIGEIRA', 'Lesão ligeira'), ('MODERADA', 'Lesão moderada'), ('GRAVE', 'Lesão grave')], default='SEM_LESAO', max_length=20, verbose_name='Consequências da queda')),
                ('lesoes_observadas', models.TextField(blank=True, verbose_name='Lesões observadas')),
                ('estado_consciencia', models.CharField(choices=[('ALERTA', 'Alerta'), ('CONFUSO', 'Confuso'), ('SONOLENTO', 'Sonolento'), ('INCONSCIENTE', 'Inconsciente'), ('NAO_AVALIADO', 'Não avaliado')], default='ALERTA', max_length=20, verbose_name='Estado de consciência')),
                ('sinais_vitais', models.TextField(blank=True, help_text='Registe tensão arterial, pulso, saturação, glicemia ou outras avaliações.', verbose_name='Sinais vitais e avaliação')),
                ('nivel_dor', models.PositiveSmallIntegerField(blank=True, help_text='Escala de 0 a 10.', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Nível de dor')),
                ('intervencoes_realizadas', models.TextField(help_text='Indique os cuidados, avaliações e medidas tomadas imediatamente após a queda.', verbose_name='Intervenções realizadas')),
                ('medidas_preventivas', models.TextField(blank=True, help_text='Indique as medidas implementadas para reduzir o risco de nova queda.', verbose_name='Medidas preventivas adotadas')),
                ('medico_informado', models.BooleanField(default=False, verbose_name='Médico informado')),
                ('familia_informada', models.BooleanField(default=False, verbose_name='Família ou responsável informado')),
                ('encaminhado_urgencia', models.BooleanField(default=False, verbose_name='Encaminhado para urgência')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações adicionais')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('registo_enfermagem', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='queda', to='enfermagem.registoenfermagem', verbose_name='Registo de Enfermagem')),
            ],
            options={
                'verbose_name': 'Registo de queda',
                'verbose_name_plural': 'Registos de quedas',
                'ordering': ['-data_hora_queda', '-criado_em'],
            },
        ),
        migrations.AddField(
            model_name='registoenfermagem',
            name='tipo_registo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registos', to='enfermagem.tiporegistoenfermagem', verbose_name='Tipo de registo'),
        ),
        migrations.AddField(
            model_name='registoenfermagem',
            name='utente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registos_enfermagem', to='visitas.utente', verbose_name='Utente'),
        ),
        migrations.CreateModel(
            name='HistoricoRegistoQueda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(choices=[('CRIADO', 'Registo criado'), ('ALTERADO', 'Registo alterado')], max_length=20, verbose_name='Ação')),
                ('dados', models.JSONField(default=dict, verbose_name='Dados guardados')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Data da alteração')),
                ('profissional', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historico_quedas_registado', to=settings.AUTH_USER_MODEL, verbose_name='Alterado por')),
                ('registo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historico', to='enfermagem.registoqueda', verbose_name='Registo de queda')),
            ],
            options={
                'verbose_name': 'Histórico de registo de queda',
                'verbose_name_plural': 'Histórico dos registos de quedas',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='HistoricoRegistoEnfermagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(choices=[('CRIADO', 'Registo criado'), ('ALTERADO', 'Registo alterado')], max_length=20, verbose_name='Ação')),
                ('dados', models.JSONField(default=dict, verbose_name='Dados guardados')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Data da alteração')),
                ('profissional', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historico_enfermagem_registado', to=settings.AUTH_USER_MODEL, verbose_name='Alterado por')),
                ('registo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historico', to='enfermagem.registoenfermagem', verbose_name='Registo de Enfermagem')),
            ],
            options={
                'verbose_name': 'Histórico de registo de Enfermagem',
                'verbose_name_plural': 'Histórico dos registos de Enfermagem',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.AddIndex(
            model_name='registoqueda',
            index=models.Index(fields=['data_hora_queda'], name='enf_queda_data'),
        ),
        migrations.AddIndex(
            model_name='registoqueda',
            index=models.Index(fields=['gravidade'], name='enf_queda_gravidade'),
        ),
        migrations.AddIndex(
            model_name='registoenfermagem',
            index=models.Index(fields=['utente', 'data_registo'], name='enf_reg_utente_data'),
        ),
        migrations.AddIndex(
            model_name='registoenfermagem',
            index=models.Index(fields=['profissional', 'data_registo'], name='enf_reg_prof_data'),
        ),
        migrations.AddIndex(
            model_name='registoenfermagem',
            index=models.Index(fields=['visibilidade'], name='enf_reg_visibilidade'),
        ),
        migrations.AddIndex(
            model_name='historicoregistoqueda',
            index=models.Index(fields=['registo', 'criado_em'], name='enf_hist_queda_data'),
        ),
        migrations.AddIndex(
            model_name='historicoregistoenfermagem',
            index=models.Index(fields=['registo', 'criado_em'], name='enf_hist_reg_data'),
        ),
    ]
