# Generated by Django 4.2.9 on 2026-08-29 23:26

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('enfermagem', '0002_configurar_tipos_iniciais'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registoqueda',
            options={'ordering': ['-data_hora_queda', '-criado_em'], 'verbose_name': 'Ficha de notificação de queda', 'verbose_name_plural': 'Fichas de notificação de quedas'},
        ),
        migrations.RemoveIndex(
            model_name='historicoregistoenfermagem',
            name='enf_hist_reg_data',
        ),
        migrations.RemoveIndex(
            model_name='historicoregistoqueda',
            name='enf_hist_queda_data',
        ),
        migrations.RemoveField(
            model_name='registoqueda',
            name='encaminhado_urgencia',
        ),
        migrations.RemoveField(
            model_name='registoqueda',
            name='estado_consciencia',
        ),
        migrations.RemoveField(
            model_name='registoqueda',
            name='familia_informada',
        ),
        migrations.RemoveField(
            model_name='registoqueda',
            name='lesoes_observadas',
        ),
        migrations.RemoveField(
            model_name='registoqueda',
            name='medico_informado',
        ),
        migrations.RemoveField(
            model_name='registoqueda',
            name='medidas_preventivas',
        ),
        migrations.RemoveField(
            model_name='registoqueda',
            name='nivel_dor',
        ),
        migrations.RemoveField(
            model_name='registoqueda',
            name='sinais_vitais',
        ),
        migrations.RemoveField(
            model_name='registoqueda',
            name='testemunhada',
        ),
        migrations.RemoveField(
            model_name='registoqueda',
            name='testemunhas',
        ),
        migrations.AddField(
            model_name='registoqueda',
            name='atividade_outra',
            field=models.CharField(blank=True, max_length=200, verbose_name='Outra atividade'),
        ),
        migrations.AddField(
            model_name='registoqueda',
            name='data_notificacao_institucional',
            field=models.DateField(blank=True, null=True, verbose_name='Data da notificação institucional'),
        ),
        migrations.AddField(
            model_name='registoqueda',
            name='diagnostico_principal',
            field=models.TextField(blank=True, verbose_name='Diagnóstico principal'),
        ),
        migrations.AddField(
            model_name='registoqueda',
            name='dispositivo_auxilio',
            field=models.CharField(blank=True, choices=[('NENHUM', 'Nenhum'), ('ANDARILHO', 'Andarilho'), ('CANADIANAS', 'Canadiana(s)'), ('BENGALA', 'Bengala'), ('CADEIRA_RODAS', 'Cadeira de rodas'), ('OUTRO', 'Outro')], max_length=30, verbose_name='Dispositivo de auxílio'),
        ),
        migrations.AddField(
            model_name='registoqueda',
            name='dispositivo_auxilio_outro',
            field=models.CharField(blank=True, max_length=200, verbose_name='Outro dispositivo de auxílio'),
        ),
        migrations.AddField(
            model_name='registoqueda',
            name='doente_estava',
            field=models.CharField(blank=True, choices=[('SOZINHO', 'Sozinho'), ('ACOMPANHANTE', 'Com acompanhante'), ('PROFISSIONAL_SAUDE', 'Com profissional de saúde'), ('NAO_DETERMINADO', 'Não determinado')], max_length=30, verbose_name='O utente estava'),
        ),
        migrations.AddField(
            model_name='registoqueda',
            name='familiar_notificado',
            field=models.CharField(blank=True, choices=[('SIM', 'Sim'), ('NAO', 'Não'), ('NAO_APLICAVEL', 'Não aplicável')], max_length=20, verbose_name='Familiar/representante notificado'),
        ),
        migrations.AddField(
            model_name='registoqueda',
            name='familiar_notificado_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data e hora da notificação ao familiar'),
        ),
        migrations.AddField(
            model_name='registoqueda',
            name='fator_contribuinte_outro',
            field=models.CharField(blank=True, max_length=200, verbose_name='Outro fator contribuinte'),
        ),
        migrations.AddField(
            model_name='registoqueda',
            name='grades_laterais',
            field=models.CharField(blank=True, choices=[('LEVANTADAS', 'Levantadas'), ('BAIXADAS', 'Baixadas'), ('NAO_APLICAVEL', 'Não aplicável'), ('DESCONHECIDO', 'Desconhecido')], max_length=30, verbose_name='Grades laterais da cama'),
        ),
        migrations.AddField(
            model_name='registoqueda',
            name='identificacao_utente',
            field=models.JSONField(blank=True, default=dict, verbose_name='Identificação do utente'),
        ),
        migrations.AddField(
            model_name='registoqueda',
            name='intervencao_outra',
            field=models.CharField(blank=True, max_length=250, verbose_name='Outra intervenção'),
        ),
        migrations.AddField(
            model_name='registoqueda',
            name='lesao_outra',
            field=models.CharField(blank=True, max_length=200, verbose_name='Outra lesão'),
        ),
        migrations.AddField(
            model_name='registoqueda',
            name='lesoes_identificadas',
            field=models.JSONField(blank=True, default=list, verbose_name='Lesões identificadas'),
        ),
        migrations.AddField(
            model_name='registoqueda',
            name='localizacao_outra',
            field=models.CharField(blank=True, max_length=200, verbose_name='Outra localização'),
        ),
        migrations.AddField(
            model_name='registoqueda',
            name='localizacoes_lesao',
            field=models.JSONField(blank=True, default=list, verbose_name='Localização das lesões'),
        ),
        migrations.AddField(
            model_name='registoqueda',
            name='medico_assistente',
            field=models.CharField(blank=True, max_length=200, verbose_name='Médico assistente'),
        ),
        migrations.AddField(
            model_name='registoqueda',
            name='medico_nao_notificado_justificacao',
            field=models.TextField(blank=True, verbose_name='Justificação para médico não notificado'),
        ),
        migrations.AddField(
            model_name='registoqueda',
            name='medico_notificado',
            field=models.CharField(blank=True, choices=[('SIM', 'Sim'), ('NAO', 'Não')], max_length=10, verbose_name='Médico notificado'),
        ),
        migrations.AddField(
            model_name='registoqueda',
            name='medico_notificado_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data e hora da notificação ao médico'),
        ),
        migrations.AddField(
            model_name='registoqueda',
            name='medida_corretiva_outra',
            field=models.CharField(blank=True, max_length=250, verbose_name='Outra medida corretiva'),
        ),
        migrations.AddField(
            model_name='registoqueda',
            name='medidas_corretivas',
            field=models.JSONField(blank=True, default=list, verbose_name='Medidas corretivas implementadas'),
        ),
        migrations.AddField(
            model_name='registoqueda',
            name='medidas_preventivas_implementadas',
            field=models.CharField(blank=True, choices=[('SIM', 'Sim'), ('NAO', 'Não'), ('PARCIALMENTE', 'Parcialmente')], max_length=20, verbose_name='Medidas preventivas implementadas'),
        ),
        migrations.AddField(
            model_name='registoqueda',
            name='morse_aplicada',
            field=models.CharField(blank=True, choices=[('SIM', 'Sim'), ('NAO', 'Não')], max_length=10, verbose_name='Escala de Morse aplicada antes da queda'),
        ),
        migrations.AddField(
            model_name='registoqueda',
            name='nivel_risco_previo',
            field=models.CharField(choices=[('BAIXO', 'Baixo risco — inferior a 25'), ('MODERADO', 'Risco moderado — 25 a 50'), ('ALTO', 'Alto risco — 51 ou superior'), ('NAO_AVALIADO', 'Não avaliado')], default='NAO_AVALIADO', max_length=20, verbose_name='Nível de risco anterior'),
        ),
        migrations.AddField(
            model_name='registoqueda',
            name='notificacao_institucional_estado',
            field=models.CharField(choices=[('SIM', 'Sim'), ('NAO', 'Não'), ('PENDENTE', 'Pendente')], default='PENDENTE', max_length=20, verbose_name='Introduzido no sistema de notificação'),
        ),
        migrations.AddField(
            model_name='registoqueda',
            name='reavaliacao_morse_estado',
            field=models.CharField(blank=True, choices=[('REALIZADA', 'Realizada'), ('PENDENTE', 'Pendente'), ('NAO_APLICAVEL', 'Não aplicável')], max_length=20, verbose_name='Reavaliação Morse pós-queda'),
        ),
        migrations.AddField(
            model_name='registoqueda',
            name='score_morse_pos',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(125)], verbose_name='Novo score Morse'),
        ),
        migrations.AddField(
            model_name='registoqueda',
            name='score_morse_previo',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(125)], verbose_name='Score Morse anterior'),
        ),
        migrations.AddField(
            model_name='registoqueda',
            name='servico_unidade',
            field=models.CharField(blank=True, max_length=150, verbose_name='Serviço/unidade'),
        ),
        migrations.AlterField(
            model_name='historicoregistoenfermagem',
            name='profissional',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historico_enfermagem_registado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='historicoregistoenfermagem',
            name='registo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historico', to='enfermagem.registoenfermagem'),
        ),
        migrations.AlterField(
            model_name='historicoregistoqueda',
            name='profissional',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historico_quedas_registado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='historicoregistoqueda',
            name='registo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historico', to='enfermagem.registoqueda'),
        ),
        migrations.AlterField(
            model_name='registoenfermagem',
            name='observacao',
            field=models.TextField(verbose_name='Observação e evolução'),
        ),
        migrations.AlterField(
            model_name='registoenfermagem',
            name='visibilidade',
            field=models.CharField(choices=[('CONFIDENCIAL', 'Apenas eu'), ('GRUPO', 'Grupo profissional'), ('TODOS', 'Equipas clínicas autorizadas')], default='TODOS', max_length=20, verbose_name='Visibilidade'),
        ),
        migrations.AlterField(
            model_name='registoqueda',
            name='atividade_no_momento',
            field=models.CharField(blank=True, choices=[('LEVANTE_CAMA', 'Levante da cama'), ('DEAMBULACAO', 'Deambulação'), ('TRANSFERENCIA', 'Transferência'), ('USO_WC', 'Uso de WC ou arrastadeira'), ('BANHO', 'Banho'), ('OUTRA', 'Outra')], max_length=30, verbose_name='Atividade no momento'),
        ),
        migrations.AlterField(
            model_name='registoqueda',
            name='descricao_ocorrencia',
            field=models.TextField(verbose_name='Descrição da queda'),
        ),
        migrations.AlterField(
            model_name='registoqueda',
            name='fatores_contribuintes',
            field=models.JSONField(blank=True, default=list, verbose_name='Fatores contribuintes'),
        ),
        migrations.AlterField(
            model_name='registoqueda',
            name='gravidade',
            field=models.CharField(choices=[('SEM_LESAO', 'Sem lesão'), ('MINOR', 'Lesão minor — equimose ou abrasão'), ('MODERADA', 'Lesão moderada'), ('MAJOR', 'Lesão major'), ('MORTE', 'Morte')], default='SEM_LESAO', max_length=20, verbose_name='Grau de lesão'),
        ),
        migrations.AlterField(
            model_name='registoqueda',
            name='intervencoes_realizadas',
            field=models.JSONField(blank=True, default=list, verbose_name='Intervenções efetuadas'),
        ),
        migrations.AlterField(
            model_name='registoqueda',
            name='local_detalhe',
            field=models.CharField(blank=True, max_length=200, verbose_name='Outro local'),
        ),
        migrations.AlterField(
            model_name='registoqueda',
            name='local_queda',
            field=models.CharField(choices=[('QUARTO_CAMA', 'Quarto/cama'), ('CASA_BANHO', 'Casa de banho'), ('CORREDOR', 'Corredor'), ('EXTERIOR', 'Exterior'), ('OUTRO', 'Outro')], max_length=30, verbose_name='Local exato'),
        ),
        migrations.AlterField(
            model_name='registoqueda',
            name='observacoes',
            field=models.TextField(blank=True, verbose_name='Observações/seguimento'),
        ),
        migrations.AlterField(
            model_name='registoqueda',
            name='tipo_queda',
            field=models.CharField(choices=[('ACIDENTAL', 'Acidental — fatores ambientais'), ('FISIOLOGICA', 'Fisiológica — doença ou medicação'), ('COMPORTAMENTAL', 'Comportamental — incumprimento'), ('NAO_DETERMINADA', 'Não determinada')], max_length=30, verbose_name='Tipo de queda'),
        ),
        migrations.AlterField(
            model_name='tiporegistoenfermagem',
            name='codigo',
            field=models.SlugField(unique=True, verbose_name='Código'),
        ),
        migrations.AddIndex(
            model_name='registoqueda',
            index=models.Index(fields=['notificacao_institucional_estado'], name='enf_queda_notificacao'),
        ),
    ]
