# Generated by Django 4.2.9 on 2026-08-29 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enfermagem', '0003_alter_registoqueda_options_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='historicoregistoenfermagem',
            index=models.Index(fields=['registo', 'criado_em'], name='enf_hist_reg_data'),
        ),
        migrations.AddIndex(
            model_name='historicoregistoqueda',
            index=models.Index(fields=['registo', 'criado_em'], name='enf_hist_queda_data'),
        ),
    ]
