# Generated by Django 4.2.9 on 2026-08-31 11:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('visitas', '0009_transporte_confirmado_em_transporte_confirmado_por'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('enfermagem', '0004_historicoregistoenfermagem_enf_hist_reg_data_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AusenciaUtente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('AGUDIZACAO', 'Agudização'), ('TRANSFERENCIA', 'Transferência'), ('OUTRA', 'Outra ausência')], db_index=True, default='AGUDIZACAO', max_length=20, verbose_name='Tipo de ausência')),
                ('data_hora_inicio', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Data e hora da saída')),
                ('data_hora_fim_prevista', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Regresso previsto')),
                ('data_hora_regresso', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Data e hora do regresso')),
                ('destino', models.CharField(blank=True, help_text='Ex.: Serviço de Urgência, hospital ou outra unidade.', max_length=200, verbose_name='Destino')),
                ('motivo', models.TextField(verbose_name='Motivo da ausência')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('estado', models.CharField(choices=[('ATIVA', 'Ausente'), ('TERMINADA', 'Regressou'), ('CANCELADA', 'Registo cancelado')], db_index=True, default='ATIVA', max_length=15, verbose_name='Estado')),
                ('estado_atualizado_em', models.DateTimeField(blank=True, null=True, verbose_name='Estado atualizado em')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ausencias_utentes_criadas', to=settings.AUTH_USER_MODEL, verbose_name='Registado por')),
                ('estado_atualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ausencias_utentes_atualizadas', to=settings.AUTH_USER_MODEL, verbose_name='Estado atualizado por')),
                ('utente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ausencias_enfermagem', to='visitas.utente', verbose_name='Utente')),
            ],
            options={
                'verbose_name': 'Agudização/transferência',
                'verbose_name_plural': 'Agudizações/transferências',
                'ordering': ['-data_hora_inicio', '-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='HistoricoAusenciaUtente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(choices=[('CRIADA', 'Ausência registada'), ('ALTERADA', 'Período alterado'), ('TERMINADA', 'Regresso registado'), ('CANCELADA', 'Registo cancelado')], max_length=20, verbose_name='Ação')),
                ('dados', models.JSONField(default=dict, verbose_name='Dados guardados')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Data da alteração')),
                ('ausencia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historico', to='enfermagem.ausenciautente', verbose_name='Ausência')),
                ('profissional', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historico_ausencias_registado', to=settings.AUTH_USER_MODEL, verbose_name='Profissional')),
            ],
            options={
                'verbose_name': 'Histórico de ausência',
                'verbose_name_plural': 'Histórico das ausências',
                'ordering': ['-criado_em'],
                'indexes': [models.Index(fields=['ausencia', 'criado_em'], name='enf_hist_aus_data')],
            },
        ),
        migrations.AddIndex(
            model_name='ausenciautente',
            index=models.Index(fields=['utente', 'estado'], name='enf_aus_utente_estado'),
        ),
        migrations.AddIndex(
            model_name='ausenciautente',
            index=models.Index(fields=['estado', 'data_hora_inicio'], name='enf_aus_estado_inicio'),
        ),
        migrations.AddConstraint(
            model_name='ausenciautente',
            constraint=models.UniqueConstraint(condition=models.Q(('estado', 'ATIVA')), fields=('utente',), name='enf_ausencia_ativa_unica'),
        ),
    ]
