# Generated by Django 4.2.9 on 2026-08-29 15:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('visitas', '0009_transporte_confirmado_em_transporte_confirmado_por'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ParticipacaoFisioterapia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('AGENDADO', 'Agendado'), ('REALIZADO', 'Realizou'), ('FALTOU', 'Faltou'), ('CANCELADO', 'Cancelado'), ('CANCELADO_ALTA', 'Cancelado por alta')], db_index=True, default='AGENDADO', max_length=20, verbose_name='Estado')),
                ('motivo_estado', models.CharField(blank=True, max_length=250, verbose_name='Motivo da alteração')),
                ('estado_atualizado_em', models.DateTimeField(blank=True, null=True, verbose_name='Estado atualizado em')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('estado_atualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='presencas_fisioterapia_validadas', to=settings.AUTH_USER_MODEL, verbose_name='Estado atualizado por')),
            ],
            options={
                'verbose_name': 'Participação em fisioterapia',
                'verbose_name_plural': 'Participações em fisioterapia',
                'ordering': ['sessao__inicio', 'utente__nome'],
            },
        ),
        migrations.CreateModel(
            name='SessaoFisioterapia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=180, verbose_name='Título')),
                ('tipo', models.CharField(choices=[('INDIVIDUAL', 'Individual'), ('GRUPO', 'Grupo')], default='INDIVIDUAL', max_length=15, verbose_name='Tipo de sessão')),
                ('inicio', models.DateTimeField(db_index=True, verbose_name='Início')),
                ('fim', models.DateTimeField(verbose_name='Fim')),
                ('local', models.CharField(blank=True, max_length=150, verbose_name='Local')),
                ('trabalho_planeado', models.TextField(blank=True, verbose_name='Trabalho planeado')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações de organização')),
                ('estado', models.CharField(choices=[('AGENDADA', 'Agendada'), ('REALIZADA', 'Realizada'), ('CANCELADA', 'Cancelada')], db_index=True, default='AGENDADA', max_length=15, verbose_name='Estado')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('profissional', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessoes_fisioterapia', to=settings.AUTH_USER_MODEL, verbose_name='Fisioterapeuta responsável')),
                ('utentes', models.ManyToManyField(related_name='sessoes_fisioterapia', through='fisioterapia.ParticipacaoFisioterapia', to='visitas.utente', verbose_name='Utentes')),
            ],
            options={
                'verbose_name': 'Sessão de fisioterapia',
                'verbose_name_plural': 'Sessões de fisioterapia',
                'ordering': ['inicio'],
            },
        ),
        migrations.CreateModel(
            name='RegistoFisioterapia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_registo', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Data do atendimento')),
                ('tipo_trabalho', models.CharField(max_length=180, verbose_name='Tipo de trabalho')),
                ('trabalho_realizado', models.TextField(verbose_name='Trabalho realizado')),
                ('resposta_utente', models.TextField(blank=True, verbose_name='Resposta/evolução do utente')),
                ('plano_seguinte', models.TextField(blank=True, verbose_name='Plano para a próxima sessão')),
                ('visibilidade', models.CharField(choices=[('CONFIDENCIAL', 'Apenas eu'), ('GRUPO', 'Grupo profissional'), ('TODOS', 'Todos os profissionais clínicos')], default='TODOS', max_length=15, verbose_name='Visibilidade')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('participacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registos_clinicos', to='fisioterapia.participacaofisioterapia', verbose_name='Participação')),
                ('profissional', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registos_fisioterapia', to=settings.AUTH_USER_MODEL, verbose_name='Fisioterapeuta')),
                ('utente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registos_fisioterapia', to='visitas.utente', verbose_name='Utente')),
            ],
            options={
                'verbose_name': 'Registo de fisioterapia',
                'verbose_name_plural': 'Registos de fisioterapia',
                'ordering': ['-data_registo'],
            },
        ),
        migrations.AddField(
            model_name='participacaofisioterapia',
            name='sessao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participacoes', to='fisioterapia.sessaofisioterapia', verbose_name='Sessão'),
        ),
        migrations.AddField(
            model_name='participacaofisioterapia',
            name='utente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='participacoes_fisioterapia', to='visitas.utente', verbose_name='Utente'),
        ),
        migrations.CreateModel(
            name='HistoricoParticipacaoFisioterapia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_anterior', models.CharField(blank=True, choices=[('AGENDADO', 'Agendado'), ('REALIZADO', 'Realizou'), ('FALTOU', 'Faltou'), ('CANCELADO', 'Cancelado'), ('CANCELADO_ALTA', 'Cancelado por alta')], max_length=20, verbose_name='Estado anterior')),
                ('estado_novo', models.CharField(choices=[('AGENDADO', 'Agendado'), ('REALIZADO', 'Realizou'), ('FALTOU', 'Faltou'), ('CANCELADO', 'Cancelado'), ('CANCELADO_ALTA', 'Cancelado por alta')], max_length=20, verbose_name='Novo estado')),
                ('alterado_em', models.DateTimeField(auto_now_add=True)),
                ('motivo', models.CharField(blank=True, max_length=250, verbose_name='Motivo')),
                ('alterado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alteracoes_fisioterapia', to=settings.AUTH_USER_MODEL, verbose_name='Alterado por')),
                ('participacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico', to='fisioterapia.participacaofisioterapia', verbose_name='Participação')),
            ],
            options={
                'verbose_name': 'Histórico da participação',
                'verbose_name_plural': 'Histórico das participações',
                'ordering': ['-alterado_em'],
            },
        ),
        migrations.AddIndex(
            model_name='sessaofisioterapia',
            index=models.Index(fields=['inicio', 'estado'], name='fisio_sessao_inicio_estado'),
        ),
        migrations.AddIndex(
            model_name='registofisioterapia',
            index=models.Index(fields=['utente', 'data_registo'], name='fisio_registo_utente_data'),
        ),
        migrations.AddIndex(
            model_name='participacaofisioterapia',
            index=models.Index(fields=['utente', 'estado'], name='fisio_utente_estado'),
        ),
        migrations.AddConstraint(
            model_name='participacaofisioterapia',
            constraint=models.UniqueConstraint(fields=('sessao', 'utente'), name='fisio_participacao_unica'),
        ),
    ]
