# Generated by Django 4.2.9 on 2026-08-29 16:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fisioterapia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoIntervencaoFisioterapia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('AVALIACAO', 'Avaliação'), ('FISIOTERAPIA', 'Fisioterapia'), ('REABILITACAO', 'Reabilitação'), ('TREINO_FUNCIONAL', 'Treino funcional'), ('OUTRO', 'Outro')], db_index=True, default='FISIOTERAPIA', max_length=20, verbose_name='Categoria')),
                ('nome', models.CharField(max_length=150, unique=True, verbose_name='Designação')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('ativo', models.BooleanField(db_index=True, default=True, verbose_name='Disponível para utilização')),
                ('ordem', models.PositiveSmallIntegerField(default=0, verbose_name='Ordem de apresentação')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tipo de intervenção de fisioterapia',
                'verbose_name_plural': 'Tipos de intervenção de fisioterapia',
                'ordering': ['ordem', 'categoria', 'nome'],
            },
        ),
        migrations.RemoveField(
            model_name='sessaofisioterapia',
            name='titulo',
        ),
        migrations.AddField(
            model_name='sessaofisioterapia',
            name='criado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessoes_fisioterapia_criadas', to=settings.AUTH_USER_MODEL, verbose_name='Criado por'),
        ),
        migrations.AddField(
            model_name='sessaofisioterapia',
            name='estado_atualizado_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Estado atualizado em'),
        ),
        migrations.AddField(
            model_name='sessaofisioterapia',
            name='estado_atualizado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessoes_fisioterapia_validadas', to=settings.AUTH_USER_MODEL, verbose_name='Estado atualizado por'),
        ),
        migrations.AddField(
            model_name='sessaofisioterapia',
            name='local_realizacao',
            field=models.CharField(choices=[('SALA_REABILITACAO', 'Sala de reabilitação'), ('LEITO', 'Leito/quarto do utente'), ('OUTRO', 'Outro local')], db_index=True, default='SALA_REABILITACAO', max_length=25, verbose_name='Local de realização'),
        ),
        migrations.AlterField(
            model_name='registofisioterapia',
            name='tipo_trabalho',
            field=models.CharField(blank=True, max_length=180, verbose_name='Descrição complementar da intervenção'),
        ),
        migrations.AlterField(
            model_name='sessaofisioterapia',
            name='local',
            field=models.CharField(blank=True, help_text='Preencher quando escolher outro local ou quando for necessário indicar mais detalhes.', max_length=150, verbose_name='Especificação do local'),
        ),
        migrations.AlterField(
            model_name='sessaofisioterapia',
            name='tipo',
            field=models.CharField(choices=[('INDIVIDUAL', 'Individual'), ('GRUPO', 'Grupo')], db_index=True, default='INDIVIDUAL', max_length=15, verbose_name='Formato da sessão'),
        ),
        migrations.AlterField(
            model_name='sessaofisioterapia',
            name='trabalho_planeado',
            field=models.TextField(blank=True, verbose_name='Trabalho e objetivos planeados'),
        ),
        migrations.AddIndex(
            model_name='sessaofisioterapia',
            index=models.Index(fields=['profissional', 'inicio'], name='fisio_profissional_inicio'),
        ),
        migrations.AddIndex(
            model_name='sessaofisioterapia',
            index=models.Index(fields=['local_realizacao', 'inicio'], name='fisio_local_inicio'),
        ),
        migrations.AddField(
            model_name='registofisioterapia',
            name='tipos_intervencao',
            field=models.ManyToManyField(blank=True, related_name='registos', to='fisioterapia.tipointervencaofisioterapia', verbose_name='Tipos de intervenção realizados'),
        ),
        migrations.AddField(
            model_name='sessaofisioterapia',
            name='tipos_intervencao',
            field=models.ManyToManyField(blank=True, related_name='sessoes', to='fisioterapia.tipointervencaofisioterapia', verbose_name='Tipos de intervenção'),
        ),
    ]
