# Generated by Django 4.2.9 on 2026-08-31 11:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enfermagem', '0005_ausenciautente_historicoausenciautente_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fisioterapia', '0003_configurar_tipos_iniciais'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registofisioterapia',
            options={'ordering': ['-data_registo'], 'verbose_name': 'Registo de Reabilitação', 'verbose_name_plural': 'Registos de Reabilitação'},
        ),
        migrations.AlterModelOptions(
            name='sessaofisioterapia',
            options={'ordering': ['inicio'], 'verbose_name': 'Sessão de Reabilitação', 'verbose_name_plural': 'Sessões de Reabilitação'},
        ),
        migrations.AddField(
            model_name='historicoparticipacaofisioterapia',
            name='ausencia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historico_participacoes_reabilitacao', to='enfermagem.ausenciautente', verbose_name='Ausência relacionada'),
        ),
        migrations.AddField(
            model_name='participacaofisioterapia',
            name='cancelada_por_ausencia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='participacoes_reabilitacao_canceladas', to='enfermagem.ausenciautente', verbose_name='Ausência que originou o cancelamento'),
        ),
        migrations.AddField(
            model_name='registofisioterapia',
            name='area',
            field=models.CharField(choices=[('FISIOTERAPIA', 'Fisioterapia'), ('TERAPIA_OCUPACIONAL', 'Terapia Ocupacional'), ('TERAPIA_FALA', 'Terapia da Fala')], db_index=True, default='FISIOTERAPIA', max_length=30, verbose_name='Área de Reabilitação'),
        ),
        migrations.AddField(
            model_name='sessaofisioterapia',
            name='area',
            field=models.CharField(choices=[('FISIOTERAPIA', 'Fisioterapia'), ('TERAPIA_OCUPACIONAL', 'Terapia Ocupacional'), ('TERAPIA_FALA', 'Terapia da Fala')], db_index=True, default='FISIOTERAPIA', max_length=30, verbose_name='Área de Reabilitação'),
        ),
        migrations.AlterField(
            model_name='historicoparticipacaofisioterapia',
            name='estado_anterior',
            field=models.CharField(blank=True, choices=[('AGENDADO', 'Agendado'), ('REALIZADO', 'Realizou'), ('FALTOU', 'Faltou'), ('CANCELADO', 'Cancelado'), ('CANCELADO_ALTA', 'Cancelado por alta'), ('CANCELADO_AUSENCIA', 'Cancelado por ausência')], max_length=20, verbose_name='Estado anterior'),
        ),
        migrations.AlterField(
            model_name='historicoparticipacaofisioterapia',
            name='estado_novo',
            field=models.CharField(choices=[('AGENDADO', 'Agendado'), ('REALIZADO', 'Realizou'), ('FALTOU', 'Faltou'), ('CANCELADO', 'Cancelado'), ('CANCELADO_ALTA', 'Cancelado por alta'), ('CANCELADO_AUSENCIA', 'Cancelado por ausência')], max_length=20, verbose_name='Novo estado'),
        ),
        migrations.AlterField(
            model_name='participacaofisioterapia',
            name='estado',
            field=models.CharField(choices=[('AGENDADO', 'Agendado'), ('REALIZADO', 'Realizou'), ('FALTOU', 'Faltou'), ('CANCELADO', 'Cancelado'), ('CANCELADO_ALTA', 'Cancelado por alta'), ('CANCELADO_AUSENCIA', 'Cancelado por ausência')], db_index=True, default='AGENDADO', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='participacaofisioterapia',
            name='motivo_estado',
            field=models.CharField(blank=True, max_length=250, verbose_name='Motivo da falta ou alteração'),
        ),
        migrations.AlterField(
            model_name='registofisioterapia',
            name='profissional',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registos_fisioterapia', to=settings.AUTH_USER_MODEL, verbose_name='Profissional de Reabilitação'),
        ),
        migrations.AlterField(
            model_name='sessaofisioterapia',
            name='profissional',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessoes_fisioterapia', to=settings.AUTH_USER_MODEL, verbose_name='Profissional responsável'),
        ),
        migrations.AddIndex(
            model_name='registofisioterapia',
            index=models.Index(fields=['area', 'data_registo'], name='reab_reg_area_data'),
        ),
        migrations.AddIndex(
            model_name='sessaofisioterapia',
            index=models.Index(fields=['area', 'inicio'], name='reab_area_inicio'),
        ),
    ]
