# Generated by Django 4.2.9 on 2026-08-29 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaClinica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.SlugField(help_text='Identificador interno da área. Exemplo: enfermagem ou fisioterapia.', unique=True, verbose_name='Código da área')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome da área')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('ativa', models.BooleanField(default=True, verbose_name='Área ativa')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('grupos_partilha_geral', models.ManyToManyField(blank=True, help_text="Estas equipas podem consultar os registos com visibilidade 'Equipas clínicas autorizadas'.", related_name='areas_clinicas_partilhadas', to='auth.group', verbose_name='Equipas com acesso geral')),
                ('grupos_responsaveis', models.ManyToManyField(blank=True, help_text="Estas equipas podem criar registos nesta área e consultar os registos com visibilidade 'Grupo profissional'.", related_name='areas_clinicas_responsaveis', to='auth.group', verbose_name='Equipas responsáveis')),
            ],
            options={
                'verbose_name': 'Configuração de área clínica',
                'verbose_name_plural': 'Configurações das áreas clínicas',
                'ordering': ['nome'],
                'indexes': [models.Index(fields=['codigo', 'ativa'], name='clinica_area_codigo_ativa')],
            },
        ),
    ]
