# Generated by Django 4.2.9 on 2026-08-30 00:56

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoDieta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.SlugField(max_length=60, unique=True, verbose_name='Código')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Tipo de dieta')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('ordem', models.PositiveSmallIntegerField(default=0, verbose_name='Ordem')),
            ],
            options={
                'verbose_name': 'Tipo de dieta',
                'verbose_name_plural': 'Tipos de dieta',
                'ordering': ['ordem', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='TipoRefeicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.SlugField(max_length=60, unique=True, verbose_name='Código')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Tipo de refeição')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('ordem', models.PositiveSmallIntegerField(default=0, verbose_name='Ordem')),
            ],
            options={
                'verbose_name': 'Tipo de refeição',
                'verbose_name_plural': 'Tipos de refeição',
                'ordering': ['ordem', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='UnidadeCozinha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.SlugField(max_length=40, unique=True, verbose_name='Código')),
                ('nome', models.CharField(max_length=120, unique=True, verbose_name='Unidade/piso')),
                ('ativa', models.BooleanField(default=True, verbose_name='Ativa')),
                ('ordem', models.PositiveSmallIntegerField(default=0, verbose_name='Ordem')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('enfermeiros', models.ManyToManyField(blank=True, help_text='Profissionais autorizados a criar e confirmar pedidos desta unidade ou piso.', related_name='unidades_cozinha_atribuidas', to=settings.AUTH_USER_MODEL, verbose_name='Profissionais de Enfermagem')),
            ],
            options={
                'verbose_name': 'Unidade/piso da Cozinha',
                'verbose_name_plural': 'Unidades/pisos da Cozinha',
                'ordering': ['ordem', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='ProdutoCozinha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.SlugField(max_length=80, unique=True, verbose_name='Código')),
                ('nome', models.CharField(max_length=150, unique=True, verbose_name='Produto')),
                ('categoria', models.CharField(choices=[('AGUA', 'Água'), ('BEBIDA', 'Outra bebida'), ('BOLACHA', 'Bolacha'), ('LACTICINIO', 'Laticínio'), ('PAPA_FARINHA', 'Papa/farinha'), ('PAO_SANDES', 'Pão/sandes'), ('SOPA_SOBREMESA', 'Sopa/sobremesa'), ('CONSUMIVEL', 'Consumível'), ('OUTRO', 'Outro')], default='OUTRO', max_length=30, verbose_name='Categoria')),
                ('unidade_medida', models.CharField(choices=[('UN', 'Unidade'), ('EMB', 'Embalagem'), ('PCT', 'Pacote'), ('GAR', 'Garrafa'), ('L', 'Litro'), ('POR', 'Porção'), ('OUTRA', 'Outra')], default='UN', max_length=10, verbose_name='Unidade de medida')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('ordem', models.PositiveSmallIntegerField(default=0, verbose_name='Ordem')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Produto da Cozinha',
                'verbose_name_plural': 'Produtos da Cozinha',
                'ordering': ['ordem', 'nome'],
                'indexes': [models.Index(fields=['ativo', 'ordem'], name='coz_prod_ativo_ordem')],
            },
        ),
        migrations.CreateModel(
            name='PedidoCozinha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_servico', models.DateField(db_index=True, verbose_name='Data do pedido/serviço')),
                ('estado', models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('ENVIADO', 'Enviado'), ('REABERTO', 'Reaberto para correção'), ('EM_PREPARACAO', 'Em preparação'), ('ENTREGUE', 'Entregue'), ('CONFIRMADO', 'Confirmado'), ('DIVERGENCIA', 'Com divergência'), ('CANCELADO', 'Cancelado')], db_index=True, default='RASCUNHO', max_length=25, verbose_name='Estado')),
                ('observacoes_enfermagem', models.TextField(blank=True, verbose_name='Observações da Enfermagem')),
                ('observacoes_cozinha', models.TextField(blank=True, verbose_name='Observações da Cozinha')),
                ('observacoes_confirmacao', models.TextField(blank=True, verbose_name='Observações da confirmação')),
                ('enviado_em', models.DateTimeField(blank=True, null=True, verbose_name='Enviado em')),
                ('preparacao_em', models.DateTimeField(blank=True, null=True, verbose_name='Preparação iniciada em')),
                ('entregue_em', models.DateTimeField(blank=True, null=True, verbose_name='Entregue em')),
                ('confirmado_em', models.DateTimeField(blank=True, null=True, verbose_name='Confirmado em')),
                ('reaberto_em', models.DateTimeField(blank=True, null=True, verbose_name='Reaberto em')),
                ('motivo_reabertura', models.TextField(blank=True, verbose_name='Motivo da reabertura')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('confirmado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pedidos_cozinha_confirmados', to=settings.AUTH_USER_MODEL, verbose_name='Confirmado por')),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos_cozinha_criados', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('entregue_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pedidos_cozinha_entregues', to=settings.AUTH_USER_MODEL, verbose_name='Entrega registada por')),
                ('enviado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pedidos_cozinha_enviados', to=settings.AUTH_USER_MODEL, verbose_name='Enviado por')),
                ('preparacao_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pedidos_cozinha_em_preparacao', to=settings.AUTH_USER_MODEL, verbose_name='Preparação iniciada por')),
                ('reaberto_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pedidos_cozinha_reabertos', to=settings.AUTH_USER_MODEL, verbose_name='Reaberto por')),
                ('unidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to='cozinha.unidadecozinha', verbose_name='Unidade/piso')),
            ],
            options={
                'verbose_name': 'Pedido diário à Cozinha',
                'verbose_name_plural': 'Pedidos diários à Cozinha',
                'ordering': ['-data_servico', 'unidade_id'],
            },
        ),
        migrations.CreateModel(
            name='LinhaRefeicaoPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_solicitada', models.PositiveIntegerField(default=0, verbose_name='Quantidade solicitada')),
                ('quantidade_preparada', models.PositiveIntegerField(blank=True, null=True, verbose_name='Quantidade preparada')),
                ('quantidade_entregue', models.PositiveIntegerField(blank=True, null=True, verbose_name='Quantidade entregue')),
                ('quantidade_recebida', models.PositiveIntegerField(blank=True, null=True, verbose_name='Quantidade recebida')),
                ('quantidade_consumida', models.PositiveIntegerField(blank=True, null=True, verbose_name='Quantidade consumida')),
                ('observacao_enfermagem', models.CharField(blank=True, max_length=250, verbose_name='Observação da Enfermagem')),
                ('observacao_cozinha', models.CharField(blank=True, max_length=250, verbose_name='Observação da Cozinha')),
                ('observacao_confirmacao', models.CharField(blank=True, max_length=250, verbose_name='Observação da confirmação')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linhas_refeicoes', to='cozinha.pedidocozinha', verbose_name='Pedido')),
                ('tipo_dieta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='linhas_pedido', to='cozinha.tipodieta', verbose_name='Tipo de dieta')),
                ('tipo_refeicao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='linhas_pedido', to='cozinha.tiporefeicao', verbose_name='Tipo de refeição')),
            ],
            options={
                'verbose_name': 'Refeição do pedido',
                'verbose_name_plural': 'Refeições do pedido',
                'ordering': ['tipo_refeicao__ordem', 'tipo_dieta__ordem'],
            },
        ),
        migrations.CreateModel(
            name='LinhaProdutoPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_solicitada', models.DecimalField(decimal_places=2, default=0, max_digits=8, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Quantidade solicitada')),
                ('quantidade_preparada', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Quantidade preparada')),
                ('quantidade_entregue', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Quantidade entregue')),
                ('quantidade_recebida', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Quantidade recebida')),
                ('quantidade_consumida', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Quantidade consumida')),
                ('observacao_enfermagem', models.CharField(blank=True, max_length=250, verbose_name='Observação da Enfermagem')),
                ('observacao_cozinha', models.CharField(blank=True, max_length=250, verbose_name='Observação da Cozinha')),
                ('observacao_confirmacao', models.CharField(blank=True, max_length=250, verbose_name='Observação da confirmação')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linhas_produtos', to='cozinha.pedidocozinha', verbose_name='Pedido')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='linhas_pedido', to='cozinha.produtocozinha', verbose_name='Produto')),
            ],
            options={
                'verbose_name': 'Produto do pedido',
                'verbose_name_plural': 'Produtos do pedido',
                'ordering': ['produto__ordem', 'produto__nome'],
            },
        ),
        migrations.CreateModel(
            name='HistoricoPedidoCozinha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(choices=[('CRIADO', 'Criado'), ('ALTERADO', 'Quantidades alteradas'), ('ENVIADO', 'Enviado à Cozinha'), ('REABERTO', 'Reaberto para correção'), ('EM_PREPARACAO', 'Iniciada a preparação'), ('ENTREGUE', 'Entrega registada'), ('CONFIRMADO', 'Receção confirmada'), ('DIVERGENCIA', 'Divergência registada'), ('CONSUMO', 'Consumo registado'), ('CANCELADO', 'Cancelado')], max_length=25, verbose_name='Ação')),
                ('estado_anterior', models.CharField(blank=True, choices=[('RASCUNHO', 'Rascunho'), ('ENVIADO', 'Enviado'), ('REABERTO', 'Reaberto para correção'), ('EM_PREPARACAO', 'Em preparação'), ('ENTREGUE', 'Entregue'), ('CONFIRMADO', 'Confirmado'), ('DIVERGENCIA', 'Com divergência'), ('CANCELADO', 'Cancelado')], max_length=25, verbose_name='Estado anterior')),
                ('estado_novo', models.CharField(blank=True, choices=[('RASCUNHO', 'Rascunho'), ('ENVIADO', 'Enviado'), ('REABERTO', 'Reaberto para correção'), ('EM_PREPARACAO', 'Em preparação'), ('ENTREGUE', 'Entregue'), ('CONFIRMADO', 'Confirmado'), ('DIVERGENCIA', 'Com divergência'), ('CANCELADO', 'Cancelado')], max_length=25, verbose_name='Novo estado')),
                ('dados', models.JSONField(blank=True, default=dict, verbose_name='Dados do pedido')),
                ('observacao', models.TextField(blank=True, verbose_name='Observação')),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Criado em')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico', to='cozinha.pedidocozinha', verbose_name='Pedido')),
                ('profissional', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historico_pedidos_cozinha', to=settings.AUTH_USER_MODEL, verbose_name='Profissional')),
            ],
            options={
                'verbose_name': 'Histórico do pedido da Cozinha',
                'verbose_name_plural': 'Histórico dos pedidos da Cozinha',
                'ordering': ['-criado_em', '-pk'],
            },
        ),
        migrations.AddIndex(
            model_name='pedidocozinha',
            index=models.Index(fields=['data_servico', 'estado'], name='coz_pedido_data_estado'),
        ),
        migrations.AddIndex(
            model_name='pedidocozinha',
            index=models.Index(fields=['unidade', 'data_servico'], name='coz_pedido_unidade_data'),
        ),
        migrations.AddConstraint(
            model_name='pedidocozinha',
            constraint=models.UniqueConstraint(fields=('unidade', 'data_servico'), name='coz_pedido_unidade_data_unico'),
        ),
        migrations.AddConstraint(
            model_name='linharefeicaopedido',
            constraint=models.UniqueConstraint(fields=('pedido', 'tipo_refeicao', 'tipo_dieta'), name='coz_linha_refeicao_unica'),
        ),
        migrations.AddConstraint(
            model_name='linhaprodutopedido',
            constraint=models.UniqueConstraint(fields=('pedido', 'produto'), name='coz_linha_produto_unica'),
        ),
        migrations.AddIndex(
            model_name='historicopedidocozinha',
            index=models.Index(fields=['pedido', 'criado_em'], name='coz_hist_pedido_data'),
        ),
    ]
