# Generated by Django 4.2.9 on 2026-08-30 21:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cozinha', '0002_dados_iniciais'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pedidocozinha',
            options={'ordering': ['-data_servico', 'unidade_id', 'tipo', '-criado_em'], 'verbose_name': 'Pedido à Cozinha', 'verbose_name_plural': 'Pedidos à Cozinha'},
        ),
        migrations.RemoveConstraint(
            model_name='pedidocozinha',
            name='coz_pedido_unidade_data_unico',
        ),
        migrations.RemoveIndex(
            model_name='pedidocozinha',
            name='coz_pedido_data_estado',
        ),
        migrations.AddField(
            model_name='pedidocozinha',
            name='tipo',
            field=models.CharField(choices=[('REFEICOES', 'Pedido de refeições'), ('SUPLEMENTOS', 'Pedido de suplementos')], db_index=True, default='SUPLEMENTOS', max_length=20, verbose_name='Tipo de pedido'),
        ),
        migrations.AlterField(
            model_name='unidadecozinha',
            name='enfermeiros',
            field=models.ManyToManyField(blank=True, related_name='unidades_cozinha_atribuidas', to=settings.AUTH_USER_MODEL, verbose_name='Profissionais de Enfermagem'),
        ),
        migrations.AddIndex(
            model_name='pedidocozinha',
            index=models.Index(fields=['tipo', 'data_servico', 'estado'], name='coz_pedido_tipo_data_estado'),
        ),
        migrations.AddConstraint(
            model_name='pedidocozinha',
            constraint=models.UniqueConstraint(condition=models.Q(('tipo', 'REFEICOES'), models.Q(('estado', 'CANCELADO'), _negated=True)), fields=('unidade', 'data_servico'), name='coz_refeicao_unidade_data_ativa'),
        ),
        migrations.AddConstraint(
            model_name='pedidocozinha',
            constraint=models.UniqueConstraint(condition=models.Q(('estado__in', ['RASCUNHO', 'ENVIADO', 'REABERTO', 'EM_PREPARACAO']), ('tipo', 'SUPLEMENTOS')), fields=('unidade',), name='coz_suplemento_aberto_unidade'),
        ),
    ]
