# Generated by Django 4.2.9 on 2026-09-01 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cozinha', '0003_alter_pedidocozinha_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linhaprodutopedido',
            name='quantidade_consumida',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Quantidade consumida'),
        ),
        migrations.AlterField(
            model_name='linhaprodutopedido',
            name='quantidade_entregue',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Quantidade entregue'),
        ),
        migrations.AlterField(
            model_name='linhaprodutopedido',
            name='quantidade_preparada',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Quantidade preparada'),
        ),
        migrations.AlterField(
            model_name='linhaprodutopedido',
            name='quantidade_recebida',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Quantidade recebida'),
        ),
        migrations.AlterField(
            model_name='linhaprodutopedido',
            name='quantidade_solicitada',
            field=models.PositiveIntegerField(default=0, verbose_name='Quantidade solicitada'),
        ),
    ]
